data:
  file_path: "./drive/My\ Drive/pistoBot/personal/chat_parsed/user-messages.txt"
  file_encoding: "utf-8"
  token_level: "word"
  seq_length: 3
  lowercase: True
  batch_size: 128
  buffer_size: 0 # Buffer used to shuffle the data. 0 for size = len(data)
ml:
  embedding_dim: 256
  rnn_units: 1024
  dropout: 0.3
  epochs: 30
  save_path: "./data/models_trained/"
generation:
  gen_length: 10
  n_generations: 500 # Each generation will start with one random token
  temperature: 1.0
